apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../dev/zobsai-backend-deployment-dev.yaml
  - ../../dev/zobsai-backend-config-dev.yaml
  - ../../dev/zobsai-backend-secrets-dev.yaml
  - ../../dev/zobsai-frontend-deployment-dev.yaml
  - ../../dev/zobsai-frontend-config-dev.yaml
  - ../../dev/zobsai-frontend-secrets-dev.yaml
  - ../../zobsai-redis.yaml
  - ../../zobsai-ingress-dev.yaml
  - ../../dev/zobsai-uni-company-panel-deployment-dev.yaml
  - ../../dev/zobsai-uni-company-panel-config-dev.yaml

namespace: dev-zobsai
# Optionally add a nameSuffix or namePrefix to avoid name collisions across namespaces
# nameSuffix: -dev

# refreshed: 2025-09-28T23:44:00Z
