apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../zobsai-backend-deployment.yaml
  - ../zobsai-backend-configmap.yaml
  - ../zobsai-backend-secrets.yaml
  - ../zobsai-frontend-deployment.yaml
  - ../zobsai-frontend-configs.yaml
  - ../zobsai-frontend-secrets.yaml
  - ../zobsai-redis.yaml
  - ../zobsai-ingress-dev.yaml

namespace: dev-zobsai

# Optionally add a nameSuffix or namePrefix to avoid name collisions across namespaces
# nameSuffix: -dev
