apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../manifests

namespace: dev-zobsai

# Optionally add a nameSuffix or namePrefix to avoid name collisions across namespaces
# nameSuffix: -dev
