// import { Student } from './src/models/students/student.model.js';

const userEmails = [
  'ersurajrawat@gmail.com',
  'nishadas7598@gmail.com',
  'aaradhyachoudhary827@gmail.com',
  'lakshmipathyjn8861@gmail.com',
  'urviwalia16@gmail.com',
  'adityatorgal581@gmail.com',
  'tanushri.testintern@gmail.com',
  'shivanisingh07080708@gmail.com',
  'anshityagi0405@gmail.com',
  'iamdevsingh123@gmail.com',
  'aniketsingh.dpsk@gmail.com',
  'kartiklingayat019@gmail.com',
  'desaimihir843@gmail.com',
  'kumarrohit23502@gmail.com',
  'tabishsaifee0@gmail.com',
  'yashrane332@gmail.com',
  'rohithvitteamraj@gmail.com',
  'raghuveerdsunagar@gmail.com',
  'bpatil8689857@gmail.com',
  'mithunpattabhi.vitap@gmail.com',
  'sa234393@gmail.com',
  'nishuvp15@gmail.com',
  'najinaj467@gmail.com',
  'abdulirfan1108@gmail.com',
  'sangaminagaraj01@gmail.com',
  'divanshujangid040602@gmail.com',
  'lhemanthreddy4@gmail.com',
  'sudharabishek26@gmail.com',
  'prabhasmadipadiga@gmail.com',
  'vigneshvignesh8765@gmail.com',
  'ashokjamagondiashok@gmail.com',
  's84326284@gmail.com',
  'shenoy20shri@gmail.com',
  'subhadip.pal2k@gmail.com',
  'munif.mthms@gmail.com',
  'anandcs2005@gmail.com',
  'kaustubhapundir@gmail.com',
  'aditiyasengar@gmail.com',
  'mosesoluwasanya08109@gmail.com',
  'krishnanair235@gmail.com',
  'tanushkaverma102@gmail.com',
  'kulsumahmed417@gmail.com',
  'm9522091774@gmail.com',
  'satyammayara1@gmail.com',
  'sudeshnag087@gmail.com',
  'vijay.n.mishra2003@gmail.com',
  'gokulnathnvgk007@gmail.com',
  'aveelash.hota04@gmail.com',
  'niketyadav313@gmail.com',
  'arpitad1808@gmail.com',
  'anilpachar956@gmail.com',
  'jidink011@gmail.com',
  'lokeshdadhich86963@gmail.com',
  'aakankshapatil308@gmail.com',
  'shahidsayyed777@gmail.com',
  'hemalatha0904@gmail.com',
  'kuamrv98133@gmail.com',
  'pankajmali1712003@gmail.com',
  'swapnadipkhutia@gmail.com',
  'nandinipathak559@gmail.com',
  'althafjaffery@gmail.com',
  'asifjuman56@gmail.com',
  'kalyansagar7008@gmail.com',
  'syedaummekulsum9@gmail.com',
  'selvahari399@gmail.com',
  'ditidpatel1@gmail.com',
  'choudharyankita282002@gmail.com',
  'aryan.dba@gmail.com',
  'lakshmimurali.here@gmail.com',
  'anujsavant338@gmail.com',
  'nishac1349@gmail.com',
  'kondrubhargavi216@gmail.com',
  'ys8062006@gmail.com',
  'dipakchavan2901@gmail.com',
  'hargun13singh@gmail.com',
  'madhulikachauhanweb@gmail.com',
  'mishrakumarharsh987@gmail.com',
  'shivampandey20.connect@gmail.com',
  'tanujakurane58@gmail.com',
  'kanikadogra26@gmail.com',
  'rehanajahir1234@gmail.com',
  's81153084@gmail.com',
  'sayeh.hn27@gmail.com',
  'savitathapliyal6@gmail.com',
  'chandrakishoret197@gmail.com',
  'baddamrajeshwarreddy62@gmail.com',
  'khushheart12@gmail.com',
  'reethustephen23@gmail.com',
  'ashwinshetty737@gmail.com',
  'seemaj391@gmail.com',
  'harshvardhansingh903@gmail.com',
  'shaikhaliyaa780@gmail.com',
  'ddmashish@gmail.com',
  'kaushikraman1333@gmail.com',
  'pkunj5301@gmail.com',
  'jayabijor@yahoo.com',
  'adnaan.2735@gmail.com',
  'azardeen4051@gmail.com',
  '6264069a@gmail.com',
  'ry616995@gmail.com',
  'maurya1458arjun@gmail.com',
  'sujitakula9658@gmail.com',
  'nambiaraparnapavithran@gmail.com',
  'gannekajuics@gmail.com',
  'mansidahare9@gmail.com',
  'anchalthakur12076@gmail.com',
  'advshubhamj@gmail.com',
  'hishanoor321@gmail.com',
  'bhavyasharma1726@gmail.com',
  'saranshgarg1776@gmail.com',
  'tejashreomore3004@gmail.com',
  'udayahir6360@gmail.com',
  'sasmitapadhiarybca3rdyearz2@gmail.com',
  'pavang6524@gmail.com',
  'iamparth1618@gmail.com',
  'komalaveeran6@gmail.com',
  'shasankar049@gmail.com',
  'nehabopche25@gmail.com',
  'mahammadshafi8058@gmail.com',
  'preethisara12@gmail.com',
  'muthu713k@gmail.com',
  'kp.kavitapal2601@gmail.com',
  'pahujayashika001@gmail.com',
  'itsmeardhra@gmail.com',
  'rubikamca@gmail.com',
  'meheboobpatelpatel@gmail.com',
  'furqanquazi@gmail.com',
  'abhisek1.sfi@gmail.com',
  'gouravrathore824@gmail.com',
  'pingpkb@gmail.com',
  'mishraharshitaims25@gmail.com',
  'shivanshomer77@gmail.com',
  'aryancrockroaz2@gmail.com',
  'fazilfarhan24@gmail.com',
  'adyashabiswal9938@gmail.com',
  'poorvibhatia10@gmail.com',
  'mansharaheja15@gmail.com',
  'anjalich0542@gmail.com',
  'gopiregalla3@gmail.com',
  'afreenyousuf123@gmail.com',
  'atulagarwal8221@gmail.com',
  'shubikaarora2004@gmail.com',
  'arsalan@helpstudyabroad.com',
  'surajsinghrajput1509005@gmail.com',
  'salihabhatti5@gmail.com',
  'devendranagar853@gmail.com',
  'naresh.v0725@gmail.com',
  'vinitakumarivk255@gmail.com',
  'muhammedrifahi075@gmail.com',
  'arunkumar773928@gmail.com',
  'nayanvaidya13@gmail.com',
  'sharayuyeotikar6@gmail.com',
  '2023btechaidsjatin15411@poornima.edu.in',
  'shivammehta36661@gmail.com',
  'alimaula0033@gmail.com',
  'marriindhu2001@gmail.com',
  'sinha.prakhar1994@gmail.com',
  'vinay@helpstudyabroad.com',
  'mishaathapliyal15@gmail.com',
  'nitin7253983114@gmail.com',
  'bamboriya09@gmail.com',
  'samletilavanya75@gmail.com',
  'imranialauddin1@gmail.com',
  'giteaviraj155@gmail.com',
  'medhapradip08@gmail.com',
  'yashchauhan6660@gmail.com',
  'shremyagupta@gmail.com',
  'keshavrajshukla1155@gmail.com',
  'uwakmfonawak@gmail.com',
  'mahimakumarinaini@gmail.com',
  'nehaneha09276@gmail.com',
  'jagritib19@gmail.com',
  'nitinnagaraj91@gmail.com',
  'jamesksunny1@gmail.com',
  'panchaltwinkle717@gmail.com',
  'tariqadeeba8@gmail.com',
  'rohitburman1233@gmail.com',
  'subhratagarwal1234@gmail.com',
  'shilpi6201183356@gmail.com',
  'vishalmesaredm@gmail.com',
  'kkpanch29@gmail.com',
  'amitkr132005@gmail.com',
  'arf90368@gmail.com',
  'mnjtsharma272@gmail.com',
  'vuggampoojitha73@gmail.com',
  'bhuvaneshwaran91102@gmail.com',
  'kaviyadav0499@gmail.com',
  'rajeshreeshinde9021@gmail.com',
  'parasofficial0011@gmail.com',
  'navneet08.kapoor@gmail.com',
  'priyahb503@gmail.com',
  'santhanaezhilanp@gmail.com',
  'harmeetsinghchugga@gmail.com',
  'ijajmulla@ieee.org',
  'omgupta737670@gmail.com',
  'ankitamishra8763@gmail.com',
  'hariomydv1844@gmail.com',
  'vollalasaisrikar@gmail.com',
  'almasahmad6668@gmail.com',
  'tahirsaifi413@gmail.com',
  'udaykhonde41@gmail.com',
  'pranjaliup123@gmail.com',
  'manjotsingh431658@gmail.com',
  'vivekpvrn00@gmail.com',
  'arjun558rajput@gmail.com',
  'amansoni556677@gmail.com',
  'shaiphalijaiswal978@gmail.com',
  'sandhaliya1@gmail.com',
  'tinfcyash@gmail.com',
  'thakarenayana93@gmail.com',
  'akshaytomar476@gmail.com',
  'modiaastha01@gmail.com',
  'syamamohanan57@gmail.com',
  'anulekhakoley@gmail.com',
  'cpalariya67@gmail.com',
  'akshaysharma8920045@gmail.com',
  'mohdashrafhassan098@gmail.com',
  'sandhyak23901@gmail.com',
  'prajapatitripti84@gmail.com',
  'khanarman88907@gmail.com',
  'anishsaini450@gmail.com',
  'tejaswinikharpade@gmail.com',
  'manjeetsingh880028@gmail.com',
  'vedantshimpi3114@gmail.com',
  'hashircode003@gmail.com',
  'sundriyalabhi5@gmail.com',
  'hinod691@gmail.com',
  'alapatipranavi@gmail.com',
  'priyanshu999pandey@gmail.com',
  'shawalok415@gmail.com',
  'priya9930688736@gmail.com',
  'lavakausha8@gmail.com',
  'faizpinara3439@gmail.com',
  'suryaprakash3209@gmail.com',
  'sudeepbsc02@gmail.com',
  'yvinat541@gmail.com',
  'harshitatripathi2816@gmail.com',
  'meghanabscmpcs@gmail.com',
  'soumyamarythomas@outlook.com',
  'rajthakurx5@gmail.com',
  'kamanisanju2705@gmail.com',
  'arjunaditya.karamcheti@gmail.com',
  'balajir152005@gmail.com',
  'sakshivalte1371999@gmail.com',
  'madhvirathor14@gmail.com',
  'aachalkparate@gmail.com',
  'ksharmeen93@gmail.com',
  'raushanraj.tech.ai@gmail.com',
  'jindal.pallavi11@gmail.com',
  'shivam969684@gmail.com',
  'karan.prajapati.431816@gmail.com',
  'tamirchivikas@gmail.com',
  'ritkusingh@gmail.com',
  'rohitdamer2006@gmail.com',
  'sastrulaanant@gmail.com',
  'alexgomes7357@gmail.com',
  'sumitmathpalcse@gmail.com',
  'shibshankardas000@gmail.com',
  'bkb60316@gmail.com',
  'sahubhevesh867@gmail.com',
  'chinmaysoni664@gmail.com',
  'khushbooranjan8252@gmail.com',
  'arjun.rathore1812@gmail.com',
  'kavitakumari05555@gmail.com',
  'ap4703491@gmail.com',
  'eswargagansamrat@gmail.com',
  'abimynthana2425@gmail.com',
  'satyendra.0587@gmail.com',
  'saurabhgoyal8055@gmail.com',
  'kamali.kamali0625@gmail.com',
  'achintyabanerjee771@gmail.com',
  'prathambajpai77@gmail.com',
  'darkshiva890@gmail.com',
  'as8439260@gmail.com',
  'margariitaa110@gmail.com',
  'dhekanesupriya7@gmail.com',
  'nishthabansal2@gmail.com',
  'dhananjaykashodhan60@gmail.com',
  'shubham19981@gmail.com',
  'siddemanilkumar@gmail.com',
  'mauryasaurabh9698@gmail.com',
  'chetansarambalkar@gmail.com',
  'tr565003@gmail.com',
  'gauravnegi.geeky@gmail.com',
  'sumithavineesh12@gmail.com',
  'sanojyadavdharmagatpur830@gmail.com',
  'virenpatel7120@gmail.com',
  'siddhidharne08@gmail.com',
  'somud6711@gmail.com',
  'aruyuti0@gmail.com',
  'neriatewari@gmail.com',
  'flux.amv25@gmail.com',
  'ayandippaul284@gmail.com',
  'gnana.uppunuthula@gmail.com',
  'skumararts1@gmail.com',
  'iamgde@gmail.com',
  'anuragsinghmgr24@gmail.com',
  'abhi.036807@gmail.com',
  'anujahirwar00123@gmail.com',
  'amanchandravanshi7662@gmail.com',
  'manbirss9029@gmail.com',
  'omk200622@gmail.com',
  'daminiy298@gmail.com',
  'rupamagrawal1806@gmail.com',
  'prathamrawat2004@gmail.com',
  'farsin426@gmail.com',
  'sagarmanna954@gmail.com',
  'surajpawar913@gmail.com',
  'akabhi0736@gmail.com',
  'achyutajyotighosh@gmail.com',
  'nagappamegharaj@gmail.com',
  'nagoorsaheb718@gmail.com',
  'snehalthorat005@gmail.com',
  'vinitajain87086@gmail.com',
  'ishika0970@gmail.com',
  'jainpropertiesestate@gmail.com',
  'masarratsayed@gmail.com',
  'mdsalman1837@gmail.com',
];

import * as XLSX from 'xlsx';
import * as fs from 'fs';
import connectDB, { disconnectDB } from './src/config/db.js'; // Adjust path
import { Student } from './src/models/students/student.model.js'; // Adjust path

const fetchUsersAndExport = async () => {
  try {
    // 1. Connect to Database
    await connectDB();

    console.log('🔍 Fetching students from database...');

    // 2. Query the database
    // .lean() is important here to get clean JSON objects
    const students = await Student.find({ email: { $in: userEmails } }).lean();

    if (students.length === 0) {
      console.log('⚠️ No matching students found in the database.');
      return;
    }

    // 3. Format data (Optional: clean up Mongoose-specific fields like __v)
    const sanitizedData = students.map((student) => {
      const { __v, ...rest } = student; // Removes the version key
      return rest;
    });

    // 4. Create Workbook and Worksheet
    const worksheet = XLSX.utils.json_to_sheet(sanitizedData);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Students');

    // 5. Generate file and save
    const filename = 'students_data.xlsx';
    XLSX.writeFile(workbook, filename);

    console.log(
      `✅ Success! ${students.length} records exported to ${filename}`,
    );
  } catch (err) {
    console.error('❌ Error:', err);
  } finally {
    // 6. Close DB connection
    await disconnectDB();
  }
};

fetchUsersAndExport();
