apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zobsai

resources:
  - zobsai-backend-configmap.yaml
  - zobsai-frontend-configs.yaml
  - zobsai-backend-secrets.yaml
  - zobsai-frontend-secrets.yaml
  - zobsai-redis.yaml
  - zobsai-backend-deployment.yaml
  - zobsai-frontend-deployment.yaml

# Use 'labels' instead of deprecated 'commonLabels'


images:
  - name: ghcr.io/ZobsAI-com/zobsai-backend
    newTag: latest
  - name: ghcr.io/ZobsAI-com/zobsai-frontend
    newTag: latest
