apiVersion: apps/v1
kind: Deployment
metadata:
  name: zobsai-frontend
  namespace: zobsai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zobsai-frontend
  template:
    metadata:
      labels:
        app: zobsai-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend
          image: ghcr.io/zobsai-com/zobsai-frontend:607c9039ab3f374b89eb12f8575f8049775b52c0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: 'http://zobsai-backend.zobsai.svc.cluster.local:8080'
          envFrom:
            - configMapRef:
                name: zobsai-frontend-config
            - secretRef:
                name: zobsai-frontend-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: zobsai-frontend
  namespace: zobsai
spec:
  type: NodePort
  selector:
    app: zobsai-frontend
  ports:
    - port: 3000 # Service port
      targetPort: 3000 # Container port
      nodePort: 30090 # NodePort (30000-32767)
