apiVersion: v1
kind: Secret
metadata:
  name: zobsai-backend-secrets
  namespace: zobsai
type: Opaque
stringData:
  NODE_ENV: 'production'
  MONGO_URL: ''
  RAPID_API_KEY: 'c7ba6ca0c9mshc1e7b4827328e98p1be463jsn88e70a3f4bcc'
  GOOGLE_API_KEY: 'AIzaSyBV9zLT9YX8b7NVNbxM8YDgiRwsNANJRJs'
  CLIENT_ID: '584491493872-83pvhlcutmll768clf3bom050882n3ur.apps.googleusercontent.com'
  CLIENT_SECRET: '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'
  REDIRECT_URI: 'http://localhost:8080/oauth2callback'
  EMAIL_HOST: 'smtp.gmail.com'
  EMAIL_PORT: '2525'
  EMAIL_USER: 'infozobsai@gmail.com'
  EMAIL_PASSWORD: 'wssq kdwx phtg uxzd'
  EMAIL_SECURE: 'false'
  STRIPE_SECRET_KEY: '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'
  STRIPE_WEBHOOK_SECRET: 'whsec_qTBlzItif4ppB2MqKpNQEAt0WjcdhT0S'
  CLOUDINARY_CLOUD_NAME: 'ddx9jfhzt'
  CLOUDINARY_API_KEY: '167453355555211'
  CLOUDINARY_API_SECRET: '4_IBUE_4qngNnsHx4xnhDR9tLGQ'
  GOOGLE_SERVICE_ACCOUNT_EMAIL: 'zobsai@zobsai-471610.iam.gserviceaccount.com'
  GOOGLE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCf7Ox2y4BFrkbk\n...\n-----END PRIVATE KEY-----\n"
  GOOGLE_SHEET_ID: '186eR_5n9Y-vrj48a1OjTWPJbD6G6_t33d0tj0gn2y9I'
  LINKEDIN_CLIENT_SECRET: 'WPL_AP1.xlVrZqBWsbnqXzkL.1Zaheg=='
  LINKEDIN_CLIENT_ID: '78cxzsxixqb18l'
  SITEMAP_API_KEY: 'secret'
  GOOGLE_GENERATIVE_AI_KEY: 'AIzaSyAy4pHPJEPWWDXHWw06MTGs4q4RYSTJM_M'
  GEMINI_API_KEY: AIzaSyAy4pHPJEPWWDXHWw06MTGs4q4RYSTJM_M
