apiVersion: apps/v1
kind: Deployment
metadata:
  name: zobsai-backend
  namespace: zobsai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zobsai-backend
  template:
    metadata:
      labels:
        app: zobsai-backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend
          image: ghcr.io/zobsai-com/zobsai-backend:54ce6fe003e36548c18f47c1d3d5f9a9bf7fd9ca
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: zobsai-backend-config
            - secretRef:
                name: zobsai-backend-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: zobsai-backend
  namespace: zobsai
spec:
  selector:
    app: zobsai-backend
  ports:
    - port: 8080 # Service port
      targetPort: 8080 # Container port
      nodePort: 30070 # External port on the node (must be between 30000–32767)
  type: NodePort
