apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zobsai-dev
  namespace: monitoring
  annotations:
    # Track backend and frontend images
    argocd-image-updater.argoproj.io/image-list: zobsai-backend=ghcr.io/zobsai-com/zobsai-backend, zobsai-frontend=ghcr.io/zobsai-com/zobsai-frontend
    # Always pick the latest tag
    argocd-image-updater.argoproj.io/zobsai-backend.update-strategy: latest
    argocd-image-updater.argoproj.io/zobsai-frontend.update-strategy: latest

  # Commit updated image tags back to Git (use the dev branch for the dev app)
  argocd-image-updater.argoproj.io/write-back-method: git
  argocd-image-updater.argoproj.io/git-branch: deploy/dev-zobsai-app
spec:
  project: default
  source:
    repoURL: https://github.com/ZobsAI-com/zobsai.git
  targetRevision: deploy/dev-zobsai-app
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-zobsai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
