apiVersion: apps/v1
kind: Deployment
metadata:
  name: zobsai-frontend
  namespace: zobsai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zobsai-frontend
  template:
    metadata:
      labels:
        app: zobsai-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend
          image: ghcr.io/zobsai-com/zobsai-frontend:5f4f70d35517bb643f9a710cc0e58556f8128aba
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: REACT_APP_API_URL
              value: "http://zobsai-backend.zobsai.svc.cluster.local:8000"
          envFrom:
            - secretRef:
                name: zobsai-frontend-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: zobsai-frontend
  namespace: zobsai
spec:
  selector:
    app: zobsai-frontend
  type: NodePort              # changed from LoadBalancer
  ports:
    - port: 3000              # Service port
      targetPort: 3000        # Container port
      nodePort: 30090         # NodePort (must be 30000-32767)

