apiVersion: batch/v1
kind: Job
metadata:
  name: zobsai-frontend-tests
  namespace: zobsai
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend-tests
          image: ghcr.io/zobsai-com/zobsai-frontend:dad82dc878dc662d0eb3f40b425067e6ede2b904
          command: ["sh", "-c"]
          args:
            - |
              echo "Running frontend tests..."
              npm ci
              npm test
          env:
            - name: REACT_APP_API_URL
              value: "http://zobsai-backend.zobsai.svc.cluster.local:8080"
          envFrom:
            - configMapRef:
                name: zobsai-frontend-config
            - secretRef:
                name: zobsai-frontend-secrets
