apiVersion: v1
kind: ConfigMap
metadata:
  name: zobsai-backend-config
  namespace: zobsai
data:
  SAMPLE_KEY: 'dev-value'
  REDIS_HOST: 'zobsai-redis.dev-zobsai.svc.cluster.local'
  REDIS_PORT: '6379'

  EMAIL_HOST: 'smtp.gmail.com'
  EMAIL_PORT: '2525'
  EMAIL_SECURE: 'false'
  EMAIL_USER: 'infozobsai@gmail.com'
  EMAIL_PASSWORD: 'wssq kdwx phtg uxzd'

  MONGO_URL: 'mongodb+srv://arsalan:n3nq9IZZJsOOC5Cl@careerpilot.zysihya.mongodb.net/careerpilot?retryWrites=true&w=majority&appName=careerpilot'
  RAPID_API_KEY: 'e181f48f77msh3138245c94a6f01p197d40jsn0ae1e0afe85c'

  GOOGLE_GENERATIVE_AI_KEY: 'AIzaSyDtsJoFPYH0zTBEBDcpkJxwBYKqoRiltdM'

  GOOGLE_CLIENT_ID: '433624775795-6b9tn13tt5ak25lbe8f8i80ckb87so6t.apps.googleusercontent.com'
  GOOGLE_CLIENT_SECRET: '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'

  GOOGLE_AUTH_CLIENT_ID: '433624775795-fjule3uk4anaebdvvacrgura5j6m5e5n.apps.googleusercontent.com'
  GOOGLE_AUTH_CLIENT_SECRET: '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'

  BACKEND_URL: 'https://api.dev.zobsai.com'
  FRONTEND_URL: 'https://dev.zobsai.com'

  ACCESS_TOKEN_EXPIRY: '7d'
  ACCESS_TOKEN_SECRET: 'a11d913c91c854d9122d42c2855f20f4cea45d465ec0bc155a7f952d8f32bb7815d202b7a070b0387548db0b6f2da50c6253'

  CLOUDINARY_CLOUD_NAME: 'ddx9jfhzt'
  CLOUDINARY_API_KEY: '167453355555211'
  CLOUDINARY_API_SECRET: '4_IBUE_4qngNnsHx4xnhDR9tLGQ'

  GOOGLE_SERVICE_ACCOUNT_EMAIL: 'zobsai@zobsai-471610.iam.gserviceaccount.com'
  GOOGLE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\n MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCf7Ox2y4BFrkbk\nWWsOJdNCS92yWjbPjCZH+Ea4mBNCNbx6uZCbME0IZq/MHqJJelBUQYcG1oBsEfVg\nfGhAWJOYwA1tKTwu5aPs1hV470aan6lrseA0SxC83GI5nKuB2Pnfi5a+01grG8RF\n87BZJzhPZ+z64uM0i8RJqycLZ6FeidE8cGv+UwXozGMyvnho6tIAD9+6c9jgEwqq\n0mAnDyrQWWHN+5JpXivwgigTc3da7o+YEDCfqABxjsrahi9aTVgqd2Z2JOVw+okZ\nchoLpMcYyZnHqPYesFcLriZgGiuV153FKFtd+4KYFV3gYIxU8Cqi7obkqUh9948t\nkiDyyDHfAgMBAAECggEAQ4Lu589MnR3PC4K78MMDBc+lDS+MR91wI52prS91odOx\nd1VyuDCRtGQ0/kRIWiBqXMc0yywuFnEWVt7t24wI8sjQYi6wG1QR+V7+vYi1E30n\nNjFm5mxx6mhWht+efzgrc7Uns/LgG4KjPqx624f0+4BxyA+TvpDqEfdQij37Hz7/\ne6bNztVZXtypy4o12xN4L7fKnincu3sJbrzwvm2CXofcacpE9aD84CyWWj9N9piW\n+Bk3mFLi0yC6hwPTKzBspeC8brUinAmBNq466Fozm3Lvl9WxhN+cFgWaRUoAeTOg\nM2+gpctlWbx+vf8S6qwjeXazut2rW2mG1xeA5/aLcQKBgQDYopRKTAyp+eR4COqO\nMamKgIdb/RTwXi4/9P2Y7iNd6as/4guM1el4nr4ALDacC5QLQejUbqQ/cGRBfpm8\ne5ToJ8awMCCbUiqhKY529y30IQkorB8QiyoKaXdToFusYjze3loQTi5/XfVCzbwV\ny1zj91nitqG1Vzri7aBdqI0XLQKBgQC8/FSFbl0oPiG+yHJauSh8ySuzmQ59RLti\naO7uwg079ULcOsAVRTrAhbNKppRMPMSZnNQHQEJxdq+2WcYLzE9u7zCubpGEyySw\n6mXe8WcTUWkZo4yfiuPgsFZkf2nCCSsQj5FjPIyP/suLlm2/3MVHeD326GB1liNF\nN/JH8wPUuwKBgQCgRAa4wHJN/ZVMSCxebdcjo9p/70diXAqTPkeur95yR8BtTmmF\nE2vZ1HZz4kG0R8yKV4RMRF42oItK+MH7cuHCrkqLZc95mNv4xqmi0VKp3RbNhCin\nMI01jri8oVGwwiyOJKk0juJPT892UIXpCb362K8izkHrylDCOVH+eAeJMQKBgQCL\n3NrYnSMIg2MKBOLMzbdvEprrId0dTF65qBscTDTrKMpAnqJFm6StksVr+/hIq7h8\nTxqD+0SxIDtOYwY0+RHYceC/V0kO1CDlZbPa2SGFpHx54xZRhMK9KQPnAHzOg2aB\nrR7WKJuGffU56yxyD/tYt150eunYXDLiKVN/eBRfvQKBgQCiWIbV3r1PPqJ8jcfT\ne3RVR+gI+8vIC54ixjLMNqm6ZRE4rPt51YyCOMtnAi65dW/QmNDS2YVhmWJaHIyt\nlgQ17Z2KGA6ChdPYavmIMcEV+KQNy0QsKdvL7g2eY1QsHRBFqkZ3Uq16pmjjce+M\nYV8hIXa31eCzlldLMBc0IDOCXg==\n-----END PRIVATE KEY-----\n"
  GOOGLE_SHEET_ID: '186eR_5n9Y-vrj48a1OjTWPJbD6G6_t33d0tj0gn2y9I'

  STRIPE_SECRET_KEY: 'sk_test_51S91qQIdYj6K0osborBNLjiksqgiuBB60ddQbCjcDbthPQFIjdcs5uRxTopCBj3c3umGvz3QdEJ53xwStj6yHMNE00gbzvfRAh'
  STRIPE_WEBHOOK_SECRET: 'whsec_14cabf8459bd046991020a9a05b22689e0e85acf553e55ce2f937216449053a3'
