apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zobsai-dev
  namespace: monitoring
  # Removed argocd-image-updater annotations because CI/CD will handle image updates
spec:
  project: default
  source:
    repoURL: https://github.com/ZobsAI-com/zobsai.git
    targetRevision: develop
    path: manifests/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-zobsai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
