apiVersion: batch/v1
kind: Job
metadata:
  name: zobsai-frontend-tests
  namespace: zobsai
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend-tests
          image: ghcr.io/zobsai-com/zobsai-frontend:1487bc339f73a21251ce3c400c661b59e3a43993
          command: ["sh", "-c"]
          args:
            - |
              echo "Running frontend tests..."
              npm ci
              npm run test --if-present
          env:
            - name: REACT_APP_API_URL
              value: "http://zobsai-backend.zobsai.svc.cluster.local:8080"
          envFrom:
            - configMapRef:
                name: zobsai-frontend-config
            - secretRef:
                name: zobsai-frontend-secrets
