apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - zobsai-backend-deployment-dev.yaml
  - zobsai-backend-config-dev.yaml
  - zobsai-backend-secrets-dev.yaml
  - zobsai-frontend-deployment-dev.yaml
  - zobsai-frontend-config-dev.yaml
  - zobsai-frontend-secrets-dev.yaml
  - zobsai-redis-dev.yaml
  - zobsai-ingress-dev.yaml
  - zobsai-uni-company-panel-deployment-dev.yaml
  - zobsai-uni-company-panel-config-dev.yaml
  - zobsai-uni-company-panel-secrets-dev.yaml

namespace: dev-zobsai
# refreshed overlay: 2025-09-28T23:46:00Z
