apiVersion: v1
kind: Secret
metadata:
  name: zobsai-frontend-secrets
  namespace: dev-zobsai
type: Opaque
stringData:
  GEMINI_API_KEY: 'AIzaSyBV9zLT9YX8b7NVNbxM8YDgiRwsNANJRJs'
  NEXT_PUBLIC_GOOGLE_CLIENT_ID: '584491493872-k4r3sueu3m2j7fm5ancngm9i1018qp2j.apps.googleusercontent.com'
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: 'pk_live_51P9LpzRk1I3BflpJZwwqZtdVW5cJmdivnzPqu6vtSosnfTO44dZhve6DOdtNfupRR247b18tSTU3Ziszq8Yr2Duo00XmtGeZzC'
  NEXT_PUBLIC_LOGROCKET_ID: 'jlthnd/zobsai'
  NEXT_PUBLIC_SITEMAP_API_KEY: 'secret'
  NEXT_PUBLIC_LINKEDIN_CLIENT_ID: '78cxzsxixqb18l'
