apiVersion: v1
kind: Secret
metadata:
  name: zobsai-frontend-secrets
  namespace: dev-zobsai
type: Opaque
stringData:
  GEMINI_API_KEY: 'AIzaSyBV9zLT9YX8b7NVNbxM8YDgiRwsNANJRJs'
  NEXT_PUBLIC_NODE_ENV: ' '
