apiVersion: v1
kind: ConfigMap
metadata:
  name: zobsai-frontend-config
  namespace: dev-zobsai
data:
  NEXT_PUBLIC_NODE_ENV: 'development'
  REACT_APP_API_URL: 'http://zobsai-backend.zobsai.svc.cluster.local:8000'
  NEXT_PUBLIC_SOCKET_URL: 'https://dev.zobsai.com'
