apiVersion: apps/v1
kind: Deployment
metadata:
  name: zobsai-frontend
  namespace: dev-zobsai
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    app: zobsai-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: zobsai-frontend
  template:
    metadata:
      labels:
        app: zobsai-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend
          image: ghcr.io/zobsai-com/zobsai-frontend:2481bc43c6976586916788c36c97f8cfe9468a6c
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: zobsai-frontend-config
            - secretRef:
                name: zobsai-frontend-secrets
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: zobsai-frontend
  namespace: dev-zobsai
spec:
  type: NodePort
  selector:
    app: zobsai-frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30030

