apiVersion: apps/v1
kind: Deployment
metadata:
  name: uni-company-panel # Changed _ to -
  namespace: dev-zobsai
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    app: uni-company-panel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uni-company-panel
  template:
    metadata:
      labels:
        app: uni-company-panel
    spec:
      containers:
        - name: uni-company-panel
          image: ghcr.io/zobsai-com/zobsai-uni-company-panel:345a0ba3c82a73ca2f0e1208777c076a62dc5566
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: uni-company-panel-config # Must match ConfigMap name above
            - secretRef:
                name: uni-company-panel-secrets # Ensure your Secret is also renamed to use -
---
apiVersion: v1
kind: Service
metadata:
  name: uni-company-panel
  namespace: dev-zobsai
spec:
  type: NodePort
  selector:
    app: uni-company-panel
  ports:
    - port: 3002
      targetPort: 3002
      nodePort: 30032
