apiVersion: v1
kind: ConfigMap
metadata:
  name: zobsai-frontend-config
  namespace: dev-zobsai
data:
  NEXT_PUBLIC_NODE_ENV: 'development' # Or 'development' if needed
  NEXT_PUBLIC_GOOGLE_CLIENT_ID: '584491493872-k4r3sueu3m2j7fm5ancngm9i1018qp2j.apps.googleusercontent.com'
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: 'pk_test_51P9LpzRk1I3BflpJNaDwvDKcV5HIIH0tdf13r5jE9BpBc8buZsE1RmwuByyRpbLMnBLYoTnGhf44OfzgoGqjw43z00sCxBAIhe'
  REACT_APP_API_URL: 'http://zobsai-backend.zobsai.svc.cluster.local:8000'
  NEXT_PUBLIC_SOCKET_URL: 'http://localhost:8080'
  NEXT_PUBLIC_LINKEDIN_CLIENT_ID: '78cxzsxixqb18l'
  NEXT_PUBLIC_SITEMAP_API_KEY: 'secret'
  NEXT_PUBLIC_LOGROCKET_ID: 'jlthnd/zobsai'
