apiVersion: v1
kind: Service
metadata:
  name: zobsai-uni-company-panel
  namespace: dev-zobsai
spec:
  type: NodePort
  selector:
    app: zobsai-uni-company-panel
  ports:
    - port: 3002       # Service port
      targetPort: 3002 # Container port
      nodePort: 30032  # NodePort (optional)
