---
# Backend Deployment & Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zobsai-backend
  namespace: dev-zobsai
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    app: zobsai-backend
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:  
      app: zobsai-backend
  template:
    metadata:
      labels:
        app: zobsai-backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend
          image: ghcr.io/zobsai-com/zobsai-backend:9b8f9fb8d0ddda71de2e6bb1a183af2cfb8c8b34
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: zobsai-backend-config
            - secretRef:
                name: zobsai-backend-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: zobsai-backend
  namespace: dev-zobsai
spec:
  selector:
    app: zobsai-backend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30050
  type: NodePort
