apiVersion: apps/v1
kind: Deployment
metadata:
  name: uni-company-panel # Changed _ to -
  namespace: dev-zobsai
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    app: uni-company-panel
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: uni-company-panel
  template:
    metadata:
      labels:
        app: uni-company-panel
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: uni-company-panel
          image: ghcr.io/zobsai-com/zobsai-uni-company-panel:2966c474a2e18fea0ae2afda909a06cf9c4b4ec4
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: uni-company-panel-config # Must match ConfigMap name above
            - secretRef:
                name: uni-company-panel-secrets # Ensure your Secret is also renamed to use -

