apiVersion: v1
kind: Secret
metadata:
  name: zobsai-uni-company-panel-secrets
  namespace: dev-zobsai
type: Opaque
stringData:
  MONGO_URL: "mongodb+srv://arsalan:n3nq9IZZJsOOC5Cl@careerpilot.zysihya.mongodb.net/careerpilot?retryWrites=true&w=majority&appName=careerpilot"
  RAPID_API_KEY: "e181f48f77msh3138245c94a6f01p197d40jsn0ae1e0afe85c"
