# ---------------------------
# Build Stage
# ---------------------------
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

# ---------------------------
# Runtime Stage
# ---------------------------
FROM node:20-alpine

WORKDIR /app

# Copy only what’s needed for production
COPY --from=builder /app/package*.json ./
RUN npm install --only=production

# Copy built files and public assets
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.ts ./next.config.ts

EXPOSE 3002

CMD ["npm", "start"]
